### ISSUE TITLE
UI testing

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/frontend#54]
- [x] uzh-ase-fs24/frontend#55
- [x] uzh-ase-fs24/workspace#95
- [x] uzh-ase-fs24/frontend#57
